export const article = [
    { 
    article_title: 'Нет освещение', 
    article_image: 'https://rusnord.ru/uploads/posts/2023-06/a2ccb02486498676bc574b455d3f3ceb.jpg', 
    article_status: 'Необработанное', 
    article_text: 'Не работающая лампочка на обочине дороги около дома Ауэзова 1а',
    article_type: 'Энергосбережение',
    article_adress: 'Ауэзова 1а',
    article_date_published: '29.02.2024',
    article_responsible: 'Полиция Г. Аксу',
    article_city: 'Г. Аксу',
    user_name: 'Дария Ертаева',
    user_image: 'https://uprostim.com/wp-content/uploads/2021/03/image056-90.jpg',
    department_report: '',
    department_report_image: '',
    department_report_rate: null,
},
    { 
    article_title: 'Мусор никто не убирает', 
    article_image: 'https://risovach.ru/upload/2013/12/generator/musor_37705657_orig_.jpeg', 
    article_status: 'В работе', 
    article_text: 'Не работающая лампочка на обочине дороги около дома Ауэзова 1а',
    article_type: 'Энергосбережение',
    article_adress: 'Ауэзова 1а',
    article_date_published: '27.02.2024',
    article_responsible: 'Полиция Г. Аксу',
    article_city: 'Г. Аксу',
    user_name: 'Дария Ертаева',
    user_image: 'https://uprostim.com/wp-content/uploads/2021/03/image056-90.jpg',
    department_report: '',
    department_report_image: '',
    department_report_rate: null,
},
{   
    article_title: 'Темнеет рано', 
    article_image: 'https://rusnord.ru/uploads/posts/2023-06/a2ccb02486498676bc574b455d3f3ceb.jpg', 
    article_status: 'Выполнено', 
    article_text: 'Не работающая лампочка на обочине дороги около дома Ауэзова 1а',
    article_type: 'Энергосбережение',
    article_adress: 'Ауэзова 1а',
    article_date_published: '27.02.2024',
    article_responsible: 'Полиция Г. Аксу',
    article_city: 'Г. Аксу',
    user_name: 'Дария Ертаева',
    user_image: 'https://uprostim.com/wp-content/uploads/2021/03/image056-90.jpg',
    department_report: 'Владелец автомашины привлечен к административной ответственности ст 597 КоАП РК.',
    department_report_image: 'https://paperpaper.ru/wp-content/uploads/2020/01/l7uttvwvswi.jpg',
    department_report_rate: 5,
},
]